general.import = [
    "~/.config/alacritty/themes/onedark.toml"
]

[font]
size = 17
normal = { family = "ZedMono Nerd Font", style = "Regular" }

[keyboard]
bindings = [{ key="F11", action="ToggleFullscreen" },]

[env]
term = "xterm-256color"

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true
