[font]
size = 17
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }

[keyboard]
bindings = [{ key="F11", action="ToggleFullscreen" },]

[env]
term = "xterm-256color"
