import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

[font]
size = 15
normal = { family = "Iosevka Nerd Font", style = "Regular" }

[keyboard]
bindings = [{ key="F11", action="ToggleFullscreen" },]

[env]
term = "xterm-256color"

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true
